### PR TITLE
 new linux build: Qt 5.6

### PR DESCRIPTION
**Pull request by Artiom-M**

### CODE REVIEW

**Comment by Ribtoks** [comment]
@Artiom-M Did you commit ssdll reference by accident? It points to some not-the-latest commit anyway.

**Comment by Artiom-M** [comment]
I don't know how it happend and how to fix it. I am not very keen
      with submodules. 
    
    
    On 09/03/2017 15:05, Taras Kushnir
      wrote:
    
    
      @Artiom-M Did you commit ssdll
        reference by accident? It points to some not-the-latest commit
        anyway.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Ribtoks/xpiks","title":"Ribtoks/xpiks","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Ribtoks/xpiks"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Ribtoks in #394: @Artiom-M Did you commit ssdll reference by accident? It points to some not-the-latest commit anyway."}],"action":{"name":"View Pull Request","url":"https://github.com/Ribtoks/xpiks/pull/394#issuecomment-285359527"}}}

**Comment by Ribtoks** [comment]
@Artiom-M You have `git add`ed it before pushing. Please reset your last commit `git reset --soft HEAD~1` and remove the submodule from commit `git reset src/ssdll` and later `git checkout src/ssdll` to revert it to the original

**Comment by Artiom-M** [comment]
Packages http://ovh.to/TpLWKmj

**Comment by Ribtoks** [comment]
@Artiom-M Thank you!

**Pull request merged**
