### PR TITLE
New version change

### PR DESCRIPTION
**Pull request by Artiom-M**
Alternatively you can update this file by yourself for each new version

### CODE REVIEW

**Comment by Ribtoks** [comment]
Yes, I just forgot about updating that file. Sorry.

**Comment by Ribtoks** [comment]
Btw, please squash commits like that before creating pull request

**Comment by Artiom-M** [comment]
You have to include it to release as well

**Comment by Artiom-M** [comment]
Deb package: https://mega.nz/#!Tt91RZxC!kTUw1Pah6z8dHh30QemagAaija7GHtWErZ_D93Semiw

**Comment by Ribtoks** [comment]
Perfect, thank you.

**Pull request merged**
